#!/usr/bin/env -S just --justfile
# Documentation: https://just.systems/man/en/

set allow-duplicate-recipes := true

import '../verification-service-ui/Justfile'

# Print this help
default:
    @just -l

# Serve local assets
serve: build
    static-web-server -p $PORT -d dist/assets -z
