# OpenAPI Specification Explained: https://learn.openapis.org/specification/
# Documentation: https://spec.openapis.org/oas/v3.1.1.html
# Learning OpenAPI: https://redoc.ly/docs/resources/learning-openapi/
# Learning JSON-Schema: https://www.learnjsonschema.com/
# HTTP status codes: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
# HTTP methods: https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods
# Graphical editor and test service: https://editor-next.swagger.io/
openapi: 3.1.1
info:
  version: "0.0.1"
  title: Verifiable Data Service
  description: Verifiable Data Service
  license:
    name: Apache-2.0
  contact:
    name: identinet GmbH
    url: https://identinet.io
    email: support@identinet.io

servers:
  - url: http://localhost:3011
    description: Local development server

tags:
  - name: openid4vp-wallet
    description: OpenID4VP Operations used by Wallets
  - name: openid4vp-verifier
    description: OpenID4VP Operations used by Verifiers
  - name: linked-vp
    description: Operations used to interact with Linked Verifiable Presentations

paths:
  /v1/authrequests:
    post:
      tags:
        - openid4vp-verifier
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          description: Client bearer token
          required: true
        - name: traceId
          in: header
          description: Optional trace ID for correlating requests across services.
          schema:
            type: string
            format: uuid
          required: false
        - name: nonce
          in: path
          required: true
          description: Nonce value
          schema:
            type: string
      operationId: createRequest
      summary: Creates a new OpenID4VP Authorization Request. See https://openid.net/specs/openid-4-verifiable-presentations-1_0-20.html#section-11.5.
      description: Returns Authorization Request transaction ID and request URI for submitting the response. The authorization URI needs to be extended with the nonce generated on the side of the verifier.
      # requestBody: # TODO: maybe allow the client to define the presentation definition
      responses:
        "201":
          description: Session created, returns session details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthorizationRequest"
        "401":
          description: Unauthorized.

  /v1/authrequests/{requestId}:
    parameters:
      - name: requestId
        in: path
        required: true
        description: Authorization Request ID.
        schema:
          type: string
      - name: transactionId
        in: query
        required: true
        description: Transaction ID.
        schema:
          type: string
      - name: responseCode
        in: query
        required: true
        description: Response code.
        schema:
          type: string
      - name: traceId
        in: header
        description: Optional trace ID for correlating requests across services.
        schema:
          type: string
          format: uuid
        required: false
    get:
      tags:
        - openid4vp-verifier
      operationId: getResponse
      summary: Retrieves the submitted OpenID4VP data.
      description: Returns the submitted data and the verification result.
      responses:
        "200":
          description: Submitted data and verification result.
          content:
            application/json:
              schema:
                type: object
              example: |
                { "data": {}, "verification_result": {} }
        "204":
          description: No content has been submitted, yet.
        "401":
          description: Unauthorized.

  /v1/authorize/{requestId}:
    parameters:
      - name: requestId
        in: path
        required: true
        description: Authorization Request ID.
        schema:
          type: string
      - name: traceId
        in: header
        description: Optional trace ID for correlating requests across services.
        schema:
          type: string
          format: uuid
        required: false
    get:
      tags:
        - openid4vp-wallet
      operationId: getRequest
      summary: Retrieves the OpenID4VP Authorization Request.
      description: Returns the OpenID4VP Authorization Request.
      responses:
        "200":
          description: Returns Authorization Request.
          content:
            application/json:
              example: |
                { "TODO": {} }
              schema:
                type: object
    post:
      tags:
        - openid4vp-wallet
      operationId: submitResponse
      summary: Accepts data for this Authorization Request.
      description: Returns redirect to callback URL.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            {}
            # description: See https://openid.net/specs/openid-4-verifiable-presentations-1_0-20.html#section-6.2
            # schema: {}
            # examples: {}
      responses:
        "200":
          description: Data submission successful.
          content:
            application/json:
              schema:
                type: object
                required:
                  - redirect_uri
                properties:
                  redirect_uri:
                    type: string
              example: |
                {
                  "redirect_uri": "https://client.example.org/callback#response_code=091535f699ea575c7937fa5f0f454aee"
                }
        "400":
          description: Bad Request.

  /vp:
    get:
      tags:
        - linked-vp
      operationId: getVp
      summary: Retrieves the published Verifiable Presentation, see https://identity.foundation/linked-vp/.
      description: Returns the published Verifiable Presentation.
      responses:
        "200":
          description: Returns Linked Verifiable Presentation.
          content:
            # TODO: add support for additional linked-vp types like jwt+vp
            application/json:
              schema:
                type: object
              example: |
                {
                  "@context":
                    [
                      "https://www.w3.org/ns/did/v1",
                      "https://identity.foundation/linked-vp/contexts/v1"
                    ],
                  "id": "did:example:123",
                  "verificationMethod":
                    [
                      {
                        "id": "did:example:123#_Qq0UL2Fq651Q0Fjd6TvnYE-faHiOpRlPVQcY_-tA4A",
                        "type": "JsonWebKey2020",
                        "controller": "did:example:123",
                        "publicKeyJwk":
                          {
                            "kty": "OKP",
                            "crv": "Ed25519",
                            "x": "VCpo2LMLhn6iWku8MKvSLg2ZAoC-nlOyPVQaO3FxVeQ"
                          }
                      }
                    ],
                  "service":
                    [
                      {
                        "id": "did:example:123#foo",
                        "type": "LinkedVerifiablePresentation",
                        "serviceEndpoint":
                          [
                            "https://bar.example.com/verifiable-presentation.jsonld"
                          ]
                      },
                      {
                        "id": "did:example:123#baz",
                        "type": "LinkedVerifiablePresentation",
                        "serviceEndpoint": "ipfs://bafybeihkoviema7g3gxyt6la7vd5ho32ictqbilu3wnlo3rs7ewhnp7lly/verifiable-presentation.jwt"
                      }
                    ]
                }

components:
  # parameters:
  #   forwardPathParam:
  #     name: path
  #     in: query
  #     required: true
  #     description: Path on the agent's API, e.g. /connections
  #     schema:
  #       type: string

  schemas:
    # UserId:
    #   type: string
    #   description: "User ID."

    # ForwardRequest:
    #   type: object
    #   description: "Data format depends on the aries-go request."

    # ConnectRequest:
    #   type: object
    #   properties:
    #     user:
    #       $ref: "#/components/schemas/UserId"
    #     url:
    #       type: string
    #       description: "URL of the agent."
    #   example:
    #     user: "user1"
    #     url: "http://test.1234.com:1234"

    # DeploymentRequest:
    #   type: object
    #   properties:
    #     user:
    #       $ref: "#/components/schemas/UserId"
    #   example:
    #     user: "user1"

    DID:
      type: string
      description: "Decentralized Identifier."
      # minLength: 5
      # maxLength: 64

    AuthorizationRequest:
      type: object
      properties:
        requestId:
          type: string
          description: Id of the request
          example: 777cab68-3666-4bcb-be11-8f264dc6fa1b
        transactionId:
          type: string
          description: Id of the transaction
          example: 9989e29c-89af-4cc8-b0de-af19767e67ab
        url:
          type: string
          description: FIXME
          example: "openid://localhost:3011/authorize?request=xxx"
      required:
        - requestId
        - transactionId
        - url
