# OpenAPI Specification Explained: https://learn.openapis.org/specification/
# OpenAPI Specification: https://swagger.io/specification/
# Documentation: https://spec.openapis.org/oas/v3.1.1.html
# Learning OpenAPI: https://redoc.ly/docs/resources/learning-openapi/
# Learning JSON-Schema: https://www.learnjsonschema.com/
# HTTP status codes: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
# HTTP methods: https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods
# Graphical editor and test service: https://editor-next.swagger.io/
openapi: 3.1.1
info:
  version: "0.0.1"
  title: Verification Service
  description: Verification Service
  license:
    name: Apache-2.0
  contact:
    name: identinet GmbH
    url: https://identinet.io
    email: support@identinet.io

servers:
  - url: http://localhost:3012
    description: Local development server
  - url: https://api.check.identinet.io
    description: Demo deployment

# tags:
#   - name: verification
#     description: Operations related to verification

paths:
  /v1/verification:
    get:
      operationId: getVerification
      # tags:
      #   - verification
      summary: Verify DID or URL
      description: |
        Resolves the Decentralized Identifier for the given DNS Domain name or DID and discovers and verifies Linked
        Verifiable Presentations and Credentials. Information about the identifier, the linked presentations and
        credentials and the verification result are returned.

        Related specifications:
        - DIF Well-Known DID Configuration <https://identity.foundation/.well-known/resources/did-configuration/>
        - W3C DID Resolution <https://www.w3.org/TR/did-1.0/#did-resolution>
        - DIF Linked Verifiable Presentation <https://identity.foundation/linked-vp/>
      parameters:
        - name: q
          in: query
          description: |
            DNS domain name or DID to verify.
            If no path has been specified in the URL, `/.well-known` is appended.
            `/did.json` is appended to complete the URL in any case.
          required: true
          schema:
            type: string
            format: uri
            examples:
              url:
                description: URL, only the top-level domain will be considered
                value: https://example.com
              domain:
                description: Top-level domain name
                value: sub.example.com
              did:
                description: Decentralized Identifier
                value: did:key:92cbf90d-1410-4a4e-99a5-a1470273ca4f
        - name: brief
          in: query
          description: If `true`, returns a shortened version of the verification result.
          required: false
          schema:
            type: boolean
            default: false
      responses:
        "200":
          description: Verification result.
          content:
            application/json:
              schema:
                type: object
                required:
                  - documents
                  - credentials
                  - results
                properties:
                  documents:
                    type: array
                    description: |
                      List of DID documents associated with the given URL or DID
                    items:
                      type: object
                      example: { "TODO": {} }
                  presentations:
                    type: array
                    description: |
                      List of Linked Verifiable Presentations and included Verifiable Credentials.

                      Not included if a brief result has been requested.
                    items:
                      type: object
                      example: { "TODO": {} }
                  credentials:
                    type: array
                    description: |
                      List of Verifiable Credentials listed by Linked Verifiable Presentations associated
                      with the given URL.

                      Not included if a brief result has been requested.
                    items:
                      type: object
                      example: { "TODO": {} }
                  results:
                    type: array
                    description: |
                      Detailed list of verification results per credential.

                      Not included if a brief result has been requested.
                    items:
                      type: object
                      example: { "TODO": {} }
        "400":
          description: Bad request
        "404":
          description: |
            Identifier not found for provided domain name / DID.
            Thus empty lists are returned for all properties.
          content:
            application/json:
              example: { "documents": [], "credentials": [], "results": [] }
