# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-shop
  labels:
    app: demo-shop
spec:
  selector:
    matchLabels:
      app: demo-shop
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: demo-shop
      labels:
        app: demo-shop
    spec:
      containers:
        - name: demo-shop
          image: identinet/check-demo-shop
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
          envFrom:
            - secretRef:
                name: demo-shop-env
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /_status/healthz
              port: http
          ports:
            - containerPort: 3000
              name: http
      restartPolicy: Always
