# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedded-verification-ui
  labels:
    app: embedded-verification-ui
spec:
  selector:
    matchLabels:
      app: embedded-verification-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: embedded-verification-ui
      labels:
        app: embedded-verification-ui
    spec:
      volumes:
        - name: config
          configMap:
            name: embedded-verification-ui-config
      automountServiceAccountToken: false
      containers:
        - name: embedded-verification-ui
          image: identinet/check-embedded-verification-ui:0.0.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /public/config/config.json
              subPath: config.json
          envFrom:
            - secretRef:
                name: embedded-verification-ui-env
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              memory: 100Mi
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          ports:
            - containerPort: 3000
              name: http
      restartPolicy: Always
