#!/usr/bin/env -S just --justfile
# Documentation: https://just.systems/man/en/
# Documentation: https://www.nushell.sh/book/

set allow-duplicate-recipes := true

import '../verification-service-ui/Justfile'

# Print this help
default:
    @just -l
